### ISSUE TITLE
Error in player_season_stats

### ISSUE THREAD

**Issue by TTAbwill** [djrscally/pubg_reporting#8]
Hey there,

all data seems to be loaded correctily but the player season stats. 
I get the following error:

```
2020-02-26 20:29:58,090 INFO sqlalchemy.engine.base.Engine {'player_id_1': 'account.712916eb68b24d6691437221cf8b7529', 'season_id_1': 'division.bro.official.pc-2018-04'}
2020-02-26 20:29:58,091 INFO sqlalchemy.engine.base.Engine SELECT EXISTS (SELECT 1
FROM player_season_stats
WHERE player_season_stats.player_id = %(player_id_1)s AND player_season_stats.season_id = %(season_id_1)s) AS anon_1
2020-02-26 20:29:58,091 INFO sqlalchemy.engine.base.Engine {'player_id_1': 'account.712916eb68b24d6691437221cf8b7529', 'season_id_1': 'division.bro.official.pc-2018-05'}
Traceback (most recent call last):
  File "sync.py", line 140, in <module>
    sync()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "sync.py", line 53, in sync
    __sync(api, pubgdb)
  File "sync.py", line 124, in __sync
    api.get_player_season_stats(combo)
  File "/pubg/pubg_reporting/pubg/pubg_api.py", line 154, in get_player_season_stats
    logging.debug("get_player_season_stats: {0}: {1}: {2}".format(combo[0], combo[1], json.dumps(r.json()['data']['attributes']['gameModeStats'], indent=4)))
KeyError: 'data'
```

Thanks for your work and support!

**Comment by djrscally** [comment]
Hey man. That basically means you got something other than a HTTP 200 or
429 in response to the season stats call. Can you run with --log-level
DEBUG and post the last 50 lines or so of sync.log?

**Comment by TTAbwill** [comment]
Hey there,

still got it. According to PUBG documentation i used "steam" as shard. After i changed it to "pc-eu" the error is not there anymore. 

May be something for your readme.

Bye

**Comment by djrscally** [comment]
@TTAbwill ah cool, ok. If you do a pull from master it will now read the shard out of the config file, in the form:

```
{
    "players":[
        "player1name",
        "player2name"
    ], "shard":"pc-eu"
}
```
I'll tweak the README to reference the sharding parameter a bit better.

There's also some performance improvements; which won't be noticeable if you're only syncing yourself but if there's a lot of you it should help.
